# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Swhite ★ Notes
subtitle: 星火燎原
description: 不进则退
author: Small white
language: zh-Hans
timezone:

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# nofollow
nofollow:
    enable: true
    exclude: # 不添加 nofollow 标签的连接

# hexo sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.baixiaojian.com
root: /
# permalink: :year/:month/:day/:title/
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
#theme: yilia
theme: next

# Deployment
# Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  branch: master
  repo:
    github: git@github.com:jianxiaoBai/jianxiaoBai.github.io.git
    # coding: git@git.coding.net:jianxiaoBai/jianxiaoBai.git

# deploy:
#   type: sftp
#   # host: 118.24.53.207
#   host: 192.168.2.106
#   user: pi
#   remotePath: /var/www/myblog
#   port: 22
#   privateKey: /Users/baixiaojian/.ssh/id_rsa
  # pass:
  # passphrase: [passphrase]
  # agent: $SSH_AUTH_SOCK
